### ISSUE TITLE
The weather component doesn't show values

### ISSUE THREAD

**Issue by fs0klp1** [peinan/iterm2-statusbar-components#5]
Followed all the steps in the manual, including getting API key, but still getting this:

<img width="269" alt="Screen Shot 2020-03-03 at 1 09 36 PM" src="https://user-images.githubusercontent.com/1948973/75820010-716da780-5d50-11ea-91ed-0aa3180aa160.png">

Any ideas on how to fix it?
Thanks!

**Comment by peinan** [comment]
Thanks for the report. 😃
I guess this is because the weather API format has been changed. I’ll have a look this weekend.

**Comment by peinan** [comment]
I fixed this issue. Please reinstall or sync the changes in the PR and restart this script from iTerm Script Console. Thanks.

**Comment by fs0klp1** [comment]
@peinan It's working. Thank you for the quick turnaround and great components!
